disallowWorkspaceCycles: true

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

patchedDependencies:
  '@react-three/fiber@9.4.0': patches/@react-three__fiber@9.4.0.patch
