disallowWorkspaceCycles: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - "@next/swc*"
  - "@next/third-parties"
  - "next"
  - "@next/bundle-analyzer"
  - "eslint-config-next"
  - "@next/eslint-plugin-next"
  - "@next/env"
  - "react"
  - "react-dom"

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp
  - unrs-resolver
